# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  update-theneo-docs:
    name: Update theneo API Docs
    runs-on: generic-runner
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Test theneo
        run: |
          if curl --silent --head --fail https://api.theneo.io
          then
            echo "theneo api is reachable"
          else
            echo "not"
            exit 1
          fi
    
